return {
	attack_cooldown = 1,
	attack_damage_max = 66,
	attack_damage_min = 54,
	attack_range = 200,
	cooldown_factor = 1,
	crystal_amplitude = 6,
	crystal_base_y = 75,
	crystal_period = 3,
	damage_factor_max = 1,
	damage_factor_min = 1,
	erosion_armor_reduction = 0.1,
	erosion_duration = 5,
	holy_blast_cooldown = {
		30,
		26,
		22,
	},
	holy_blast_damage_max = {
		16,
		20,
		24,
	},
	holy_blast_damage_min = {
		12,
		16,
		20,
	},
	holy_blast_damage_radius = 50,
	holy_blast_duration = {
		4,
		5,
		6,
	},
	holy_blast_price_base = 250,
	holy_blast_price_inc = 200,
	holy_blast_shake_amplitude = 0,
	holy_blast_shake_extra_duration = 0.5,
	holy_blast_shake_freq_factor = 4,
	key_label_map = {
		attack_cooldown = "普攻冷却时间(秒)",
		attack_damage_max = "普攻最大伤害",
		attack_damage_min = "普攻最小伤害",
		attack_range = "攻击范围",
		cooldown_factor = "冷却倍率",
		crystal_amplitude = "水晶漂浮幅度(像素)",
		crystal_base_y = "水晶漂浮基础Y位置(像素)",
		crystal_period = "水晶漂浮周期(秒)",
		damage_factor_max = "伤害倍率(最大)",
		damage_factor_min = "伤害倍率(最小)",
		erosion_armor_reduction = "神圣侵蚀每次减甲比例",
		erosion_duration = "神圣侵蚀持续时间(秒)",
		holy_blast_cooldown = "神圣冲击冷却(秒)",
		holy_blast_damage_max = "神圣冲击最大伤害",
		holy_blast_damage_min = "神圣冲击最小伤害",
		holy_blast_damage_radius = "神圣冲击伤害范围",
		holy_blast_duration = "神圣冲击持续时间(秒)",
		holy_blast_price_base = "神圣冲击基础价格",
		holy_blast_price_inc = "神圣冲击每级价格增量",
		holy_blast_shake_amplitude = "神圣冲击震动幅度",
		holy_blast_shake_extra_duration = "神圣冲击震动额外时长(秒)",
		holy_blast_shake_freq_factor = "神圣冲击震动频率因子",
		light_explosion_damage_max = "光爆最大伤害",
		light_explosion_damage_min = "光爆最小伤害",
		light_explosion_ray_count_base = "光爆基础射线数",
		light_explosion_ray_count_per_level = "光爆每级增加射线数",
		light_explosion_range = "光爆搜索范围",
		light_explosion_ray_duration = "光爆射线持续时间(秒)",
		light_explosion_hit_time = "光爆命中延迟(秒)",
		nuclear_meltdown_price_base = "折射阵列基础价格",
		nuclear_meltdown_price_inc = "折射阵列每级价格增量",
		sprite_tower_scale = "主塔缩放比例",
		tower_price = "塔价格",
		ultimate_damage_every = "光柱伤害间隔(秒)",
		ultimate_max_speed = "光柱移动速度(像素/秒)",
	},
	light_explosion_damage_max = 35,
	light_explosion_damage_min = 20,
	light_explosion_ray_count_base = 1,
	light_explosion_ray_count_per_level = 1,
	light_explosion_range = 200,
	light_explosion_ray_duration = 0.367,
	light_explosion_hit_time = 0.1,
	nuclear_meltdown_price_base = 225,
	nuclear_meltdown_price_inc = 150,
	sprite_tower_scale = 0.62,
	tower_price = 280,
	ultimate_damage_every = 0.25,
	ultimate_max_speed = 80,
}
